// Generated by CoffeeScript 1.6.3
(function() {
  var TestTabGroup, mainWindow, testButton, testTabGroup;

  Titanium.UI.setBackgroundColor('#fff');

  mainWindow = Titanium.UI.createWindow();

  TestTabGroup = require('ui/test/tabgroup');

  testTabGroup = new TestTabGroup();

  testButton = Titanium.UI.createButton({
    top: 160,
    width: 240,
    left: 60,
    title: "Testing"
  });

  testButton.addEventListener("click", function(e) {
    return testTabGroup.open();
  });

  mainWindow.add(testButton);

  mainWindow.open();

}).call(this);
