// Generated by CoffeeScript 1.6.2
(function() {
  var TableView;

  TableView = function(tabGroup) {
    var table, tableData;

    tableData = [
      {
        title: "Apples",
        price: "1.25"
      }, {
        title: "Grapes",
        price: "1.50"
      }, {
        title: "Oranges",
        price: "2.50"
      }
    ];
    tableData.map(function(item) {
      return item['hasChild'] = true;
    });
    table = Ti.UI.createTableView({
      data: tableData
    });
    table.addEventListener("click", function(e) {
      var DetailWindow, details;

      if (e.rowData.hasChild) {
        DetailWindow = require('ui/test/test1_detail');
        details = new DetailWindow(e.rowData);
        return tabGroup.activeTab.open(details, {
          animated: true
        });
      }
    });
    return table;
  };

  module.exports = TableView;

}).call(this);
