// Generated by CoffeeScript 1.6.2
(function() {
  var DetailWindow;

  DetailWindow = function(item) {
    var priceLabel, view, win;

    win = Ti.UI.createWindow({
      title: "Detail Test"
    });
    view = Ti.UI.createView({
      backgroundColor: 'white'
    });
    priceLabel = Ti.UI.createLabel({
      text: "price: " + item.price
    });
    view.add(priceLabel);
    win.add(view);
    return win;
  };

  module.exports = DetailWindow;

}).call(this);
