// Generated by CoffeeScript 1.6.3
(function() {
  var TableView, testTableView, win;

  win = Ti.UI.currentWindow;

  win.title = "Testing Area";

  TableView = require('ui/generic/table_view');

  testTableView = new TableView(win.tabGroup);

  win.add(testTableView);

}).call(this);
